kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ron-brain
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "brain-region=cerebral-cortex"
  - role: worker
    labels:
      brain-region: frontal-lobe
  - role: worker
    labels:
      brain-region: temporal-lobe
