apiVersion: v1
kind: Namespace
metadata:
  name: ron-brain
  labels:
    project: cerebral-scan
    subject: ron
    scan-version: "3.7.2"
  annotations:
    cerebral-git/scan-date: "2026-03-18"
    cerebral-git/warning: "VULNERABILITY DETECTED IN EXPRESSION SUBSYSTEM"
